### ISSUE TITLE
Kolumny do edycji

### ISSUE THREAD

**Issue by Szymon-Skowron** [ardium-pl/Inwentaryzacja-ng#9]
- Zrób, żeby wszystkie kolumny były edytowalne
- Ustawić odpowiednio default values, jeżeli użytkownik podczas edycji usunie całą zawartość komórki
- Kolumna _Zwolnienie art. 11n CIT_ jeśli rodzaj transakcji finansowa - odnosi się do Zwolnienie z obowiązku DCT (zwolnienie krajowe) - źródło kapitałowe
- Kolumna _Zwolnienie art. 11n CIT_ jeśli inny rodzaj transakcji - odnosi się do Zwolnienie z obowiązku DCT (zwolnienie krajowe) - pozostałe źródła
- Kolumna _Obowiązek dokumentacji_  i _TPR_ gdy Zwolnienie z obowiązku DCT (zwolnienie krajowe) - wszystkie źródła

**Comment by Szymon-Skowron** [comment]
Czy rodzaj transkacji finansowa oznacza zarówno 'Transakcja finansowa' i 'Transakcje "rajowe" finansowe' czy tylko 'Transakcja finansowa' ?

**Comment by Floressek** [comment]
done
